name: flutter_commands
description: A wrapper of Flutter commands used daily for flutter development
version: 1.0.0
homepage: https://github.com/syedmurtaza108/flutter_commands

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  args: ^2.3.1
  mason_logger: ^0.1.1
  process_run: ^0.12.3+2

executables:
  fcm:
